### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by Bastiiiiii** [mdickinson/polyhedron#6]
Is there any Paper about this algorithm? How can I cite this work?

Thank you very much!

**Comment by mdickinson** [comment]
Hi @Bastiiiiii. Thanks for your question.

There's no paper, I'm afraid: writing one is on my to-do list, but it's quite a long way down that list, and it's not getting any nearer the top. So there's been no peer-review and no independent verification of correctness: as always with random snippets of code from the internet, you should treat with extreme caution. :-)

Having said that, a vectorised NumPy version of this code has been working well in a (closed-source) application with multiple groups of users for some years now, and I continue to believe that the algorithm is sound. For what it's worth, that code did go through Enthought's usual code-review process.

On citations, there are some suggestions here: https://academia.stackexchange.com/q/14010. One of the answers to that question suggests that it should be possible for me to create a DOI reference for a GitHub repository; I'll look into that and report back.

**Comment by mdickinson** [comment]
I've tagged the current state of the code as 1.0.0, and pushed a release to Zenodo: 

https://zenodo.org/record/3246727#.XQS4vS2ZPOQ

The DOI is `10.5281/zenodo.3246727`, so you should be able to cite using something like:
```
 Mark Dickinson. (2019, June 15). mdickinson/polyhedron: Release 1.0.0 (Version 1.0.0). Zenodo. http://doi.org/10.5281/zenodo.3246727
```
(alter to taste or to journal specifications).

**Comment by mdickinson** [comment]
Closing this as answered. Please free free to comment if you have further questions.
